FROM node:16

VOLUME ["/usr/src/app"]

EXPOSE 80

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y libcap2-bin
RUN setcap 'cap_net_bind_service=+ep' /usr/local/bin/node

RUN npm install -g @angular/cli@12.2.7

ARG BUILD_APP_ENV=production
ENV APP_ENV=$BUILD_APP_ENV

RUN mkdir -m=777 /.npm

CMD npm install && ng serve --configuration=${APP_ENV-devel} --host 0.0.0.0 --port 80 --disable-host-check
